services:
  server:
    image: user1313/dev_env:latest
    volumes:
      - .:/app
    ports:
      - "8080:8080"
      - "1313:1313"
      - "3000:3000"
    command: /bin/sh -c "while sleep 1000; do :; done"
